# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('model_pic', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
